### ISSUE TITLE
[bug] Debootstrap potential missing dependency of "binutils" to provide extractor "ar"

### ISSUE THREAD

**Issue by typoworx-de** [finnix/finnix#38] opened 2022-06-27 11:28 UTC
Debootstrap is potentially missing dependency of "binutils" to provide extractor "ar". I've been trying to use finnix as "rescue" to install/debootstrap ubuntu (current LTS "jammy"), but it fails as it seems to have missing dependency to required extractor "ar" provided by binutils package usually.

**Comment by rfinnie** [comment] 2022-10-13 00:06
`binutils` isn't included with Finnix as it's a rather large package (35MB) with very little non-development use (primarily `strings`, which I've rewritten as standalone).  I think needing to install `binutils` to install jammy+ is technically reasonable, given:

1. You also already need to install `ubuntu-keyring` ahead of time
2. You are already need to pull down a lot of data anyway, since, well, `debootstrap` :)

That being said, this should definitely be documented.

([Looks like Debian will eventually be supporting zstd in `dpkg-deb`, just not immediately.](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664))

**Comment by rfinnie** [comment] 2023-03-25 19:23
zstd support is now in Debian dpkg, and will be in Finnix 125. I've confirmed it can debootstrap Ubuntu jammy without `ar`.

**Closed as completed** 2024-02-07 01:39 UTC
Labels: committed
